// 离线题库（180+ 道，覆盖 DS / CO / OS / NET / 高数 / 线代 / 概率论）
const QUIZ_POOL = [

  // ==================== 数据结构 DS ====================
  { subject: 'DS', question: '在长度为 n 的顺序表中删除第 i 个元素 (1<=i<=n)，需要移动多少个元素？', answer: 'n-i' },
  { subject: 'DS', question: '具有 n 个结点的二叉树，若采用二叉链表存储，空链域有多少个？', answer: 'n+1' },
  { subject: 'DS', question: '快速排序在什么情况下最不利（时间复杂度退化为 O(n²)）？', answer: '数据已有序（正序或逆序）' },
  { subject: 'DS', question: '哈夫曼树中是否包含度为 1 的结点？', answer: '不包含（只有度为 0 和 2 的结点）' },
  { subject: 'DS', question: 'AOE 网中，关键路径是路径长度最长还是最短的路径？', answer: '最长路径（决定工程最短完工时间）' },
  { subject: 'DS', question: '栈的特点是什么？', answer: '后进先出（LIFO）' },
  { subject: 'DS', question: '队列的特点是什么？', answer: '先进先出（FIFO）' },
  { subject: 'DS', question: 'n 个结点的完全二叉树高度是多少？', answer: '⌊log₂n⌋ + 1' },
  { subject: 'DS', question: '对二叉搜索树（BST）进行中序遍历，得到的序列有何特点？', answer: '递增有序序列' },
  { subject: 'DS', question: '图的深度优先搜索（DFS）类似于树的哪种遍历？', answer: '先序遍历' },
  { subject: 'DS', question: '图的广度优先搜索（BFS）类似于树的哪种遍历？', answer: '层序（按层）遍历' },
  { subject: 'DS', question: '堆排序的时间复杂度是多少？', answer: 'O(n log n)' },
  { subject: 'DS', question: '归并排序的空间复杂度是多少？', answer: 'O(n)' },
  { subject: 'DS', question: '基数排序是稳定排序吗？', answer: '是稳定排序' },
  { subject: 'DS', question: '顺序查找的平均查找长度（等概率）是多少？', answer: '(n+1)/2' },
  { subject: 'DS', question: '二分查找对存储结构有何要求？', answer: '有序的顺序存储（随机访问）' },
  { subject: 'DS', question: '用开放地址法中的线性探测解决散列冲突，会产生什么问题？', answer: '堆积（一次聚集）现象' },
  { subject: 'DS', question: '二叉树前序遍历访问的第一个结点是什么？', answer: '根结点' },
  { subject: 'DS', question: '完全二叉树中，编号为 i 的结点（从 1 开始）其父结点编号是多少？', answer: '⌊i/2⌋' },
  { subject: 'DS', question: '求最小生成树的经典算法有哪两种？', answer: 'Prim 算法 和 Kruskal 算法' },
  { subject: 'DS', question: 'Dijkstra 算法对图有什么限制？', answer: '不能有负权边' },
  { subject: 'DS', question: '递归调用过深可能导致什么错误？', answer: '栈溢出（Stack Overflow）' },
  { subject: 'DS', question: 'n 个结点的二叉树最大高度（退化情况）是多少？', answer: 'n（退化为链状）' },
  { subject: 'DS', question: '拓扑排序可以用来检测有向图中的什么结构？', answer: '有向环（回路）' },
  { subject: 'DS', question: '最小堆的根结点存储的是什么值？', answer: '堆中最小值' },
  { subject: 'DS', question: '冒泡排序在最好情况（输入已有序）下时间复杂度是多少？', answer: 'O(n)' },
  { subject: 'DS', question: '已知二叉树的前序遍历和中序遍历，能否唯一确定该二叉树？', answer: '能唯一确定' },
  { subject: 'DS', question: 'B 树（多路平衡查找树）所有叶结点在哪一层？', answer: '同一层（最底层）' },
  { subject: 'DS', question: '链表相比数组的主要优势是什么？', answer: '插入/删除 O(1)，无需预先分配连续空间' },
  { subject: 'DS', question: '在 n 个结点的二叉树中，度为 0 的结点比度为 2 的结点多几个？', answer: '多 1 个（n₀ = n₂ + 1）' },

  // ==================== 计算机组成原理 CO ====================
  { subject: 'CO', question: '冯·诺依曼计算机的核心思想是什么？', answer: '存储程序（程序和数据都存储在内存中）' },
  { subject: 'CO', question: 'DRAM 刷新是以什么为单位进行的？', answer: '行' },
  { subject: 'CO', question: 'Cache 地址映射方式中，哪种方式命中率最高（灵活性最强）？', answer: '全相联映射' },
  { subject: 'CO', question: '流水线中，造成控制冒险（Control Hazard）的主要原因是什么？', answer: '分支/跳转指令' },
  { subject: 'CO', question: 'IEEE 754 单精度浮点数的阶码偏置值（Bias）是多少？', answer: '127' },
  { subject: 'CO', question: '计算机五大功能部件是什么？', answer: '运算器、控制器、存储器、输入设备、输出设备' },
  { subject: 'CO', question: '在 CPU 和主存之间设置 Cache 的根本目的是什么？', answer: '解决 CPU 与主存之间的速度不匹配问题' },
  { subject: 'CO', question: '指令周期一般分为哪几个阶段？', answer: '取指（IF）、译码（ID）、执行（EX）（广义上还包括访存和写回）' },
  { subject: 'CO', question: '中断向量中存放的是什么？', answer: '中断服务程序的入口地址' },
  { subject: 'CO', question: 'DMA 方式传输数据时，CPU 何时介入？', answer: '传输开始和结束时介入，中间不参与' },
  { subject: 'CO', question: '补码的最大优点是什么？', answer: '加减法统一运算，消除了 +0 和 -0 的歧义' },
  { subject: 'CO', question: '局部性原理分为哪两种？', answer: '时间局部性和空间局部性' },
  { subject: 'CO', question: 'Cache 写回策略（Write Back）相比直写策略的优势是什么？', answer: '减少访问主存的次数，提高效率' },
  { subject: 'CO', question: 'RISC 相比 CISC 的主要特点是什么？', answer: '指令集精简、定长指令、大量寄存器、以硬件实现为主' },
  { subject: 'CO', question: 'ROM 是什么类型的存储器？', answer: '只读存储器，非易失性' },
  { subject: 'CO', question: '溢出（Overflow）和进位（Carry）有何区别？', answer: '溢出指结果超出数值表示范围；进位指最高位向更高位产生的进位' },
  { subject: 'CO', question: '流水线中结构冒险的常见解决方法是什么？', answer: '资源复制（如分离指令 Cache 和数据 Cache）或插入流水线气泡' },
  { subject: 'CO', question: 'CPU 时钟周期、机器周期、指令周期三者的包含关系？', answer: '时钟周期 < 机器周期 < 指令周期' },
  { subject: 'CO', question: '总线带宽的计算公式是什么？', answer: '总线带宽 = 总线宽度（位） × 总线频率（Hz） / 8（字节）' },
  { subject: 'CO', question: '磁盘存取时间由哪三部分组成？', answer: '寻道时间 + 旋转延迟 + 数据传输时间' },
  { subject: 'CO', question: '原码中 +0 和 -0 的表示是否相同？', answer: '不同（+0 为 00…0，-0 为 10…0）' },
  { subject: 'CO', question: '流水线吞吐率（TP）的含义是什么？', answer: '单位时间内流水线完成的任务数（或输出结果数）' },
  { subject: 'CO', question: '程序计数器（PC）的作用是什么？', answer: '存放下一条要执行指令的地址' },
  { subject: 'CO', question: '立即寻址方式中，操作数存放在哪里？', answer: '直接存放在指令中（操作数字段）' },
  { subject: 'CO', question: '什么是 Cache 缺失（Cache Miss）？', answer: '要访问的数据不在 Cache 中，需要从主存读取' },
  { subject: 'CO', question: '为什么需要数据冒险（Data Hazard）的处理？', answer: '后续指令依赖前面指令尚未写回的结果，会读到错误数据' },
  { subject: 'CO', question: 'MAR 和 MDR 分别是什么寄存器？', answer: 'MAR 是存储器地址寄存器；MDR 是存储器数据寄存器' },
  { subject: 'CO', question: '中断处理完成后，CPU 通过什么指令返回被中断的程序？', answer: '中断返回指令（IRET / RTE 等）' },
  { subject: 'CO', question: 'SRAM 和 DRAM 哪种速度更快？哪种容量更大？', answer: 'SRAM 速度更快；DRAM 容量更大（成本更低）' },
  { subject: 'CO', question: '指令系统中，操作码的位数决定了什么？', answer: '指令系统中指令的最大条数（2^n 条）' },

  // ==================== 操作系统 OS ====================
  { subject: 'OS', question: '进程与线程的本质区别是什么？', answer: '进程是资源分配单位；线程是 CPU 调度单位' },
  { subject: 'OS', question: '银行家算法主要用于解决什么问题？', answer: '死锁避免' },
  { subject: 'OS', question: '虚拟存储器的最大容量由什么决定？', answer: '计算机的地址结构（地址总线位数）' },
  { subject: 'OS', question: '在分页系统中，页面大小越大，页表越___？', answer: '越小（页表项数减少）' },
  { subject: 'OS', question: 'SPOOLing 技术是将什么设备改造为共享设备？', answer: '独占设备（如打印机）' },
  { subject: 'OS', question: '进程的三种基本状态是什么？', answer: '就绪（Ready）、运行（Running）、阻塞（Blocked）' },
  { subject: 'OS', question: '进程控制块（PCB）的作用是什么？', answer: '描述和管理进程，是进程存在的唯一标志' },
  { subject: 'OS', question: '死锁产生的四个必要条件是什么？', answer: '互斥、占有并等待、不可剥夺、循环等待' },
  { subject: 'OS', question: '预防死锁最容易实现的方法是破坏哪个条件？', answer: '破坏循环等待条件（资源有序分配法）' },
  { subject: 'OS', question: '最优页面置换算法（OPT）为什么无法实际实现？', answer: '需要预知未来的页面访问序列' },
  { subject: 'OS', question: 'LRU 页面置换算法的全称是什么？', answer: '最近最久未使用（Least Recently Used）' },
  { subject: 'OS', question: '磁盘调度 SSTF 算法的缺点是什么？', answer: '可能导致饥饿（距当前磁头远的请求长期得不到服务）' },
  { subject: 'OS', question: '生产者消费者问题中，"空缓冲区"信号量的初始值是什么？', answer: '缓冲区大小 n' },
  { subject: 'OS', question: 'P 操作和 V 操作分别对信号量做什么？', answer: 'P：减 1（wait/申请），若<0则阻塞；V：加 1（signal/释放），若≤0则唤醒' },
  { subject: 'OS', question: '系统调用与普通函数调用的本质区别是什么？', answer: '系统调用会引起 CPU 从用户态切换到内核态' },
  { subject: 'OS', question: '线程的主要优点是什么？', answer: '创建、销毁、切换开销小，同进程内线程共享地址空间和资源' },
  { subject: 'OS', question: '段页式存储管理结合了哪两种方法的优点？', answer: '分段的逻辑清晰性 + 分页的物理内存管理高效性' },
  { subject: 'OS', question: '文件物理结构（存储方式）有哪几种？', answer: '顺序（连续）结构、链接结构、索引结构' },
  { subject: 'OS', question: '优先级调度算法可能引发什么问题？如何解决？', answer: '低优先级进程饥饿；解决方法：老化（Aging）技术，随时间提升优先级' },
  { subject: 'OS', question: '内存碎片分哪两种？各由哪种存储管理方式产生？', answer: '内部碎片（分页产生）；外部碎片（分段产生）' },
  { subject: 'OS', question: '什么是抖动（Thrashing）？', answer: '进程频繁发生缺页，大部分时间消耗在换页操作上，实际执行很少' },
  { subject: 'OS', question: '进程间通信（IPC）有哪些主要方式？', answer: '管道、消息队列、共享内存、信号量、Socket、信号' },
  { subject: 'OS', question: '文件系统中，inode 存储哪些信息？', answer: '文件元数据（大小、权限、时间戳、数据块地址等），不含文件名' },
  { subject: 'OS', question: '分时系统的主要特征是什么？', answer: '多用户交互使用，CPU 时间分片轮转，响应时间短' },
  { subject: 'OS', question: '为什么分页存储没有外部碎片？', answer: '页帧大小固定，任何空闲页帧都可分配，不会产生过小的无法利用的空间' },
  { subject: 'OS', question: '什么是临界区（Critical Section）？', answer: '访问共享资源的那段代码，同一时刻只允许一个进程进入' },
  { subject: 'OS', question: 'CPU 调度算法中，时间片轮转（RR）适合哪类系统？', answer: '分时系统（交互式系统），保证每个进程都能得到响应' },
  { subject: 'OS', question: '虚拟内存的核心思想是什么？', answer: '将部分辅存空间当作内存使用，使程序可运行在比实际物理内存更大的地址空间中' },
  { subject: 'OS', question: '页表项中的有效位（Present bit）作用是什么？', answer: '标记该页是否在物理内存中，为 0 时访问触发缺页中断' },
  { subject: 'OS', question: '什么是多级反馈队列调度算法？', answer: '设置多个优先级不同的就绪队列，新进程从高优先级队列进入，时间片用完后降级' },

  // ==================== 计算机网络 NET ====================
  { subject: 'NET', question: 'OSI 模型中，路由器工作在第几层？', answer: '第三层（网络层）' },
  { subject: 'NET', question: 'TCP 三次握手中，第一次握手 SYN 的序号由什么决定？', answer: '随机生成的初始序号（ISN）' },
  { subject: 'NET', question: 'ARP 协议的作用是什么？', answer: '将 IP 地址解析为 MAC 地址' },
  { subject: 'NET', question: 'HTTP 状态码 404 表示什么？', answer: 'Not Found（请求的资源不存在）' },
  { subject: 'NET', question: 'IPv6 地址长度是多少位？', answer: '128 位' },
  { subject: 'NET', question: 'TCP 和 UDP 的主要区别是什么？', answer: 'TCP 面向连接、可靠传输；UDP 无连接、不可靠但延迟低' },
  { subject: 'NET', question: 'TCP 四次挥手后，为什么需要 TIME_WAIT 状态？', answer: '确保对端收到最后一个 ACK；防止旧连接的数据包干扰新连接' },
  { subject: 'NET', question: 'HTTP 和 HTTPS 的核心区别是什么？', answer: 'HTTPS 在 HTTP 上加了 SSL/TLS 加密层，保证数据安全' },
  { subject: 'NET', question: 'DNS 通常使用哪种传输层协议？', answer: '通常用 UDP（查询），区域传输用 TCP' },
  { subject: 'NET', question: 'TCP 滑动窗口的主要作用是什么？', answer: '流量控制（避免发送方发送过快淹没接收方）' },
  { subject: 'NET', question: 'TCP 拥塞控制包含哪几个阶段？', answer: '慢开始、拥塞避免、快重传、快恢复' },
  { subject: 'NET', question: '以太网使用什么介质访问控制方式？', answer: 'CSMA/CD（载波监听多路访问/冲突检测）' },
  { subject: 'NET', question: 'HTTP 状态码 200、301、500 分别表示什么？', answer: '200 OK；301 永久重定向；500 服务器内部错误' },
  { subject: 'NET', question: 'ICMP 协议工作在哪一层？主要作用是什么？', answer: '网络层；报告网络差错和传递控制信息（如 ping）' },
  { subject: 'NET', question: '集线器、交换机、路由器分别工作在 OSI 哪一层？', answer: '集线器-物理层；交换机-数据链路层；路由器-网络层' },
  { subject: 'NET', question: 'RIP 协议规定的最大跳数是多少？为什么？', answer: '15 跳；超过 15 跳认为目的不可达，防止路由循环无限传播' },
  { subject: 'NET', question: 'OSPF 相比 RIP 的主要优点是什么？', answer: '无跳数限制、收敛速度快、支持大规模网络、支持多路径' },
  { subject: 'NET', question: 'TCP 三次握手为什么不用两次？', answer: '两次握手无法防止历史重复连接的建立，也无法确认双向通信能力' },
  { subject: 'NET', question: 'UDP 适用于哪些场景？', answer: '实时音视频、DNS 查询、DHCP、游戏等对延迟敏感、容忍少量丢包的场景' },
  { subject: 'NET', question: 'NAT 的全称和主要作用是什么？', answer: '网络地址转换（Network Address Translation），缓解 IPv4 地址不足' },
  { subject: 'NET', question: '什么是 ARP 欺骗攻击？', answer: '攻击者发送伪造 ARP 响应，将目标 IP 映射到攻击者 MAC，实现流量劫持' },
  { subject: 'NET', question: '子网掩码的作用是什么？', answer: '区分 IP 地址中的网络部分和主机部分' },
  { subject: 'NET', question: 'TCP 可靠传输依靠哪些机制保证？', answer: '确认应答、超时重传、序号与确认号、流量控制、拥塞控制' },
  { subject: 'NET', question: 'HTTP/1.1 相比 HTTP/1.0 的主要改进是什么？', answer: '默认持久连接（Keep-Alive），减少 TCP 连接建立开销' },
  { subject: 'NET', question: '什么是 DHCP？它工作在哪一层？', answer: '动态主机配置协议，自动分配 IP；应用层协议，使用 UDP 传输' },
  { subject: 'NET', question: '帧中继（Frame Relay）和 ATM 属于哪一层技术？', answer: '数据链路层' },
  { subject: 'NET', question: 'TCP 中，FIN 报文段用于做什么？', answer: '通知对方本端不再发送数据，请求关闭连接（半关闭）' },
  { subject: 'NET', question: '滑动窗口协议中，窗口大小为 0 意味着什么？', answer: '接收方缓冲区已满，发送方必须暂停发送' },
  { subject: 'NET', question: '为什么 IP 数据报需要 TTL 字段？', answer: '防止数据包在网络中无限循环，每过一个路由器 TTL 减 1，为 0 则丢弃' },
  { subject: 'NET', question: 'CDN 的主要作用是什么？', answer: '将内容缓存到离用户最近的边缘节点，加速访问、减轻源服务器压力' },

  // ==================== 高等数学（微积分）====================
  { subject: 'Math', question: 'lim(x→0) sin x / x = ?', answer: '1（重要极限）' },
  { subject: 'Math', question: 'd/dx (ln x) = ?', answer: '1/x' },
  { subject: 'Math', question: 'd/dx (arctan x) = ?', answer: '1 / (1 + x²)' },
  { subject: 'Math', question: '定积分 ∫₀¹ x² dx = ?', answer: '1/3' },
  { subject: 'Math', question: '若 f(x) 是奇函数，则 ∫₋ₐᵃ f(x) dx = ?', answer: '0' },
  { subject: 'Math', question: '导数的定义：f\'(x₀) = ?', answer: 'lim(h→0) [f(x₀+h) - f(x₀)] / h' },
  { subject: 'Math', question: '链式法则：d/dx [f(g(x))] = ?', answer: 'f\'(g(x)) · g\'(x)' },
  { subject: 'Math', question: '罗尔定理需要满足哪三个条件？', answer: '[a,b] 上连续，(a,b) 内可导，f(a) = f(b)' },
  { subject: 'Math', question: '拉格朗日中值定理的结论是什么？', answer: '存在 ξ∈(a,b)，使得 f(b)-f(a) = f\'(ξ)(b-a)' },
  { subject: 'Math', question: '∫eˣ dx = ?', answer: 'eˣ + C' },
  { subject: 'Math', question: '∫1/x dx = ?', answer: 'ln|x| + C' },
  { subject: 'Math', question: '分部积分公式 ∫u dv = ?', answer: 'uv - ∫v du' },
  { subject: 'Math', question: '若 f\'(x₀) = 0 且 f\'\'(x₀) > 0，则 x₀ 是什么类型的点？', answer: '极小值点' },
  { subject: 'Math', question: '无穷级数收敛的必要条件是什么？', answer: '通项 aₙ → 0（但此条件不充分）' },
  { subject: 'Math', question: '等比级数 Σaᵢ 在 |q| < 1 时，求和公式是什么？', answer: 'a₁ / (1 - q)' },
  { subject: 'Math', question: 'eˣ 的泰勒展开（麦克劳林级数）是什么？', answer: '1 + x + x²/2! + x³/3! + ... = Σ(xⁿ/n!)' },
  { subject: 'Math', question: '多元函数取得极值的必要条件是什么？', answer: '所有偏导数等于 0（即驻点）' },
  { subject: 'Math', question: '二重积分的几何意义是什么？', answer: '以积分区域 D 为底、z=f(x,y) 为顶的曲顶柱体体积' },
  { subject: 'Math', question: '常微分方程 y\' = ky 的通解是什么？', answer: 'y = Ce^(kx)' },
  { subject: 'Math', question: 'lim(x→0) (1+x)^(1/x) = ?', answer: 'e（重要极限）' },
  { subject: 'Math', question: '∫sin x dx = ?', answer: '-cos x + C' },
  { subject: 'Math', question: '∫cos x dx = ?', answer: 'sin x + C' },
  { subject: 'Math', question: 'f(x) 在 x₀ 处可微与可导的关系是什么？', answer: '等价（一元函数中可微⟺可导）' },
  { subject: 'Math', question: '判断级数 Σ1/nᵖ 收敛的条件是什么？', answer: 'p > 1 时收敛，p ≤ 1 时发散（p 级数）' },
  { subject: 'Math', question: 'd/dx (arcsin x) = ?', answer: '1 / √(1-x²)' },

  // ==================== 线性代数 ====================
  { subject: 'Math', question: '若 A, B 为同阶矩阵，(AB)ᵀ = ?', answer: 'BᵀAᵀ' },
  { subject: 'Math', question: '若 A 可逆，|A⁻¹| = ?', answer: '1/|A|' },
  { subject: 'Math', question: '向量组线性无关的充要条件：其秩等于？', answer: '向量的个数' },
  { subject: 'Math', question: '矩阵特征值之和等于矩阵的什么？', answer: '迹（Trace，即主对角线元素之和）' },
  { subject: 'Math', question: '实对称矩阵的特征值都是什么数？', answer: '实数' },
  { subject: 'Math', question: '2 阶行列式 |a b; c d| = ?', answer: 'ad - bc' },
  { subject: 'Math', question: 'n×n 矩阵 A 可逆的充要条件是什么？', answer: 'r(A) = n（满秩）即 |A| ≠ 0' },
  { subject: 'Math', question: '齐次线性方程组 Ax=0 有非零解的充要条件是什么？', answer: 'r(A) < n（n 为未知数个数）' },
  { subject: 'Math', question: '非齐次线性方程组 Ax=b 有解的充要条件是什么？', answer: 'r(A) = r(A|b)（系数矩阵秩等于增广矩阵秩）' },
  { subject: 'Math', question: '若 λ 是矩阵 A 的特征值，则 A² 的特征值是什么？', answer: 'λ²' },
  { subject: 'Math', question: '实对称矩阵不同特征值对应的特征向量有什么关系？', answer: '相互正交' },
  { subject: 'Math', question: '正定矩阵的特征值有什么特点？', answer: '所有特征值都大于 0' },
  { subject: 'Math', question: '施密特正交化的目的是什么？', answer: '将线性无关向量组化为标准正交（单位正交）向量组' },
  { subject: 'Math', question: '矩阵的秩的定义是什么？', answer: '矩阵中最高阶非零子式的阶数' },
  { subject: 'Math', question: '合同变换保持矩阵的什么不变？', answer: '正惯性指数和负惯性指数（即符号差）' },
  { subject: 'Math', question: '向量 β 可由向量组 α₁,...,αₘ 线性表示的充要条件？', answer: 'r(α₁,...,αₘ) = r(α₁,...,αₘ,β)' },
  { subject: 'Math', question: 'AB = O 是否意味着 A = O 或 B = O？', answer: '不一定（矩阵乘法无消去律）' },
  { subject: 'Math', question: '矩阵 A 与 B 相似（A～B）的充要条件是什么？', answer: '存在可逆矩阵 P，使得 P⁻¹AP = B' },
  { subject: 'Math', question: '初等行变换不改变矩阵的什么？', answer: '矩阵的秩（行空间）' },
  { subject: 'Math', question: '特征值的乘积等于矩阵的什么？', answer: '行列式 |A|' },

  // ==================== 概率论与数理统计 ====================
  { subject: 'Math', question: '两事件 A、B 互斥与相互独立是什么关系？', answer: '互不蕴含：互斥指不能同时发生；独立指发生概率互不影响' },
  { subject: 'Math', question: '条件概率 P(A|B) = ?', answer: 'P(AB) / P(B)（要求 P(B) > 0）' },
  { subject: 'Math', question: '全概率公式：P(B) = ?', answer: 'Σ P(B|Aᵢ)P(Aᵢ)，其中 A₁,...,Aₙ 是样本空间的一个划分' },
  { subject: 'Math', question: '贝叶斯公式的通俗含义是什么？', answer: '由结果（果）推原因（因），计算后验概率' },
  { subject: 'Math', question: '正态分布 N(μ,σ²) 的期望和方差分别是什么？', answer: '期望 E(X) = μ，方差 D(X) = σ²' },
  { subject: 'Math', question: '二项分布 B(n,p) 的期望是什么？', answer: 'E(X) = np' },
  { subject: 'Math', question: '泊松分布 P(λ) 的期望和方差各是什么？', answer: 'E(X) = λ，D(X) = λ' },
  { subject: 'Math', question: '方差的计算公式（利用期望表示）是什么？', answer: 'D(X) = E(X²) - [E(X)]²' },
  { subject: 'Math', question: '大数定律的核心结论是什么？', answer: '当 n 足够大时，样本均值依概率收敛于总体期望（频率稳定于概率）' },
  { subject: 'Math', question: '中心极限定理的核心结论是什么？', answer: '大量独立同分布随机变量之和（或均值）近似服从正态分布' },
  { subject: 'Math', question: '协方差 Cov(X,Y) > 0 表示什么？', answer: 'X 和 Y 正相关（一个增大另一个也趋于增大）' },
  { subject: 'Math', question: '相关系数 ρ = 0 是否意味着 X 与 Y 相互独立？', answer: '不一定（线性不相关不等于独立）' },
  { subject: 'Math', question: '均匀分布 U(a,b) 的期望是什么？', answer: '(a+b)/2' },
  { subject: 'Math', question: '指数分布具有什么重要性质（与几何分布类似）？', answer: '无记忆性' },
  { subject: 'Math', question: '样本方差 S² 是总体方差 σ² 的无偏估计，即 E(S²) = ?', answer: 'σ²' },
  { subject: 'Math', question: '若 X～N(0,1)，则 X² 服从什么分布？', answer: 'χ²(1)（自由度为 1 的卡方分布）' },
  { subject: 'Math', question: '估计量的无偏性是什么含义？', answer: '估计量的期望等于被估计的总体参数真值' },
  { subject: 'Math', question: '假设检验中，第一类错误（弃真错误）的概率用什么表示？', answer: 'α（显著性水平）' },
  { subject: 'Math', question: '切比雪夫不等式的意义是什么？', answer: '不管分布如何，随机变量偏离均值超过 kσ 的概率不超过 1/k²' },
  { subject: 'Math', question: '离散型随机变量 X 的数学期望 E(X) = ?', answer: 'Σ xᵢ · P(X = xᵢ)' },

  // ==================== 补充高频考点 ====================
  // --- DS 综合 ---
  { subject: 'DS', question: '对 n 个元素进行堆排序，建初始堆需要调用多少次 adjustHeap（下沉）操作？', answer: '⌊n/2⌋ 次（从最后一个非叶结点向上依次调整）' },
  { subject: 'DS', question: '循环队列中，判断队满的条件是什么（设置标志位法和少用一个元素法）？', answer: '少用一个元素法：(rear+1)%maxSize == front；标志位法：增加 size 计数或 flag 字段' },
  { subject: 'DS', question: '二叉排序树（BST）最坏情况下查找时间复杂度是多少？什么时候发生？', answer: 'O(n)，当树退化为单支链表（插入有序序列）时发生' },
  { subject: 'DS', question: '图的关键路径中，活动的最早开始时间 e(i) 和最迟开始时间 l(i) 满足什么条件时为关键活动？', answer: 'e(i) = l(i) 时为关键活动（松弛时间为 0）' },
  { subject: 'DS', question: '将 n 个元素的无序序列建成小根堆，时间复杂度是多少？', answer: 'O(n)（线性时间，自底向上建堆）' },
  { subject: 'DS', question: '散列表的装填因子 α 越大，意味着什么？', answer: '冲突概率越大，查找效率越低；但空间利用率越高' },

  // --- CO 计算 ---
  { subject: 'CO', question: 'n 级流水线完成 k 个任务，所需时间公式是什么（各段时间相等均为 Δt）？', answer: '(n + k - 1) × Δt' },
  { subject: 'CO', question: 'Cache 命中率为 h，Cache 存取时间 tc，主存存取时间 tm，平均存取时间公式是什么？', answer: 'h × tc + (1-h) × tm（同时访问 Cache 和主存时：h × tc + (1-h) × (tc+tm)）' },
  { subject: 'CO', question: '字长为 8 位，补码 10000000 表示的十进制数是多少？', answer: '-128（补码最小负数，无对应的原码）' },
  { subject: 'CO', question: '磁盘转速 6000 rpm，则平均旋转延迟（半圈时间）是多少 ms？', answer: '5 ms（每圈 10ms，半圈 5ms）' },
  { subject: 'CO', question: 'CPU 执行时间 = 指令条数 × CPI × 时钟周期，若 CPI=2、主频=1GHz，10^9 条指令执行时间是多少？', answer: '2 秒（= 10^9 × 2 / 10^9）' },

  // --- OS 大题 ---
  { subject: 'OS', question: '读者-写者问题中，读者优先策略下，写者可能发生什么问题？', answer: '写者饥饿（starvation）——只要持续有读者，写者永远无法获得访问权' },
  { subject: 'OS', question: '分段存储和分页存储，哪种方式下程序员能感知到存储单位？', answer: '分段（段是逻辑概念，程序员显式划分代码段/数据段）；分页对程序员透明' },
  { subject: 'OS', question: '在什么情况下，增加内存物理帧数反而会导致缺页次数增加？', answer: 'Belady 异常（FIFO 置换算法可能出现该现象）' },
  { subject: 'OS', question: '进程从运行态进入阻塞态是主动还是被动行为？', answer: '主动（进程因等待 I/O 等事件主动调用阻塞原语）；运行→就绪是被动（时间片到期被剥夺）' },
  { subject: 'OS', question: '管程（Monitor）相比信号量的主要优势是什么？', answer: '把共享变量及操作封装，互斥自动实现，程序员不需要手动调用 P/V，减少死锁风险' },

  // --- NET 协议 ---
  { subject: 'NET', question: 'TCP 中 MSS（最大报文段长度）和 MTU（最大传输单元）的关系是什么？', answer: 'MSS = MTU - IP头(20B) - TCP头(20B)，以太网 MTU=1500B，则典型 MSS=1460B' },
  { subject: 'NET', question: 'HTTPS 的握手过程中，服务器的数字证书主要解决什么问题？', answer: '身份认证（防中间人攻击），确认你连的是真正的服务器而不是冒充者' },
  { subject: 'NET', question: 'IP 地址 192.168.1.0/24 中，可用主机地址有多少个？', answer: '254 个（256 - 2，减去全 0 网络地址和全 1 广播地址）' },
  { subject: 'NET', question: '为什么 UDP 的首部只有 8 字节而 TCP 首部最少 20 字节？', answer: 'UDP 无连接、不可靠，不需要序号、确认号、窗口、控制标志等字段' },
  { subject: 'NET', question: 'BGP 协议工作在哪一层？主要用于什么场景？', answer: '应用层（基于 TCP）；自治系统（AS）之间的路由选择（域间路由）' },

  // --- Math 综合 ---
  { subject: 'Math', question: '∫₀^{π/2} sin²x dx = ?', answer: 'π/4（利用 sin²x=(1-cos2x)/2 化简）' },
  { subject: 'Math', question: 'f(x) 在 [a,b] 上连续，则 d/dx [∫ₐˣ f(t)dt] = ?', answer: 'f(x)（变上限积分求导等于被积函数在上限处的值）' },
  { subject: 'Math', question: '若 X～N(μ,σ²)，标准化后 Z = (X-μ)/σ 服从什么分布？', answer: 'N(0,1)（标准正态分布）' },
  { subject: 'Math', question: '行列式按行展开：|A| = Σ aᵢⱼ Aᵢⱼ，其中 Aᵢⱼ 是什么？', answer: '元素 aᵢⱼ 的代数余子式（= (-1)^(i+j) × 对应余子式 Mᵢⱼ）' },
  { subject: 'Math', question: '非齐次线性方程组 Ax=b 解的结构：通解 = ?', answer: '一个特解 + Ax=0 的通解（齐次方程组基础解系的线性组合）' }
];

export function getRandomQuiz() {
  const now = process.env.PREVIEW_DATE ? new Date(process.env.PREVIEW_DATE + 'T08:00:00') : new Date();
  const today = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
  let hash = 0;
  for (let i = 0; i < today.length; i++) {
    hash = ((hash << 5) - hash) + today.charCodeAt(i);
    hash |= 0;
  }
  const index = Math.abs(hash) % QUIZ_POOL.length;
  return QUIZ_POOL[index];
}
